version: "3.9"  # optional since v1.27.0
services:
#   web:
#     build: .
#     ports:
#       - 8080:8080
#     environment:
#       - MYSQL_HOST=mysql-db
#     networks:
#       - employee-mysql
#     links:
#       - mysql

  mysql-db:
    image: mysql:8
    restart: always
    networks:
      - web-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    ports:
      - 0.0.0.0:3306:3306
networks:
  web-mysql: